### ISSUE TITLE
Interested in OSX support?

### ISSUE THREAD

**Issue by codeadict** [videomorph-dev/videomorph#22]
I was able to run **videomorph** on macOS Mojave with a few tweaks to the code, still very hacky   but can contribute a PR with the changes needed to support OSX and homebrew (Open Source package manager for mac) formula as well.

<img width="1096" alt="Screen Shot 2019-06-17 at 9 24 06 AM" src="https://user-images.githubusercontent.com/168440/59607831-0f95e080-90e2-11e9-8b01-87c138b29095.png">

**Comment by lpozo** [comment]
@codeadict, that's a great news. Please, do the PR and we'll check the code. The PR must be done against the `develop` branch. Thank you a lot for been interested in VideoMorph. :+1:

**Comment by codeshard** [comment]
@codeadict What a wonderful news! A pleasure that you can contribute with us. It will be an honor to review your PR! Welcome to the team and thanks in advance!

**Comment by BishopWolf** [comment]
I am still not able to open it in macos, is this still ongoing?

```bash
E15TY:videomorph alexvergaragil$ sudo python3 setup.py install
Password:
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    from videomorph.converter import VERSION
  File "/Users/alexvergaragil/Documents/GIT/videomorph/videomorph/converter/__init__.py", line 55, in <module>
    VERSION = get_version()
  File "/Users/alexvergaragil/Documents/GIT/videomorph/videomorph/converter/__init__.py", line 42, in get_version
    version_file = open(join_path(SYS_PATHS.doc, 'VERSION'),
AttributeError: 'NoneType' object has no attribute 'doc'
```

**Comment by codeadict** [comment]
Havent had the time to contribute this back, I'll see over the weekend.

**Comment by lpozo** [comment]
@BishopWolf and @codeadict. The point is that VM doesn't have paths for Mac OSX. Also, we need to implement some functions, and classes that are platform-specific. If you use the `develop` branch in its current state, then you'll be able to add these classes, and function to `vmpath.py`, and to `launchers.py` modules. Thanks both for your interest on VideoMorph.

**Comment by codeadict** [comment]
Yep, that is what i changed on my mac, unfortunately the time for me has been a bit restricted with work and kids as mentioned, most off the code is already done.

**Comment by BishopWolf** [comment]
@codeadict if you send me what you have done so far I can test it, fix all requirements and make the push request

**Comment by BishopWolf** [comment]
@codeadict  OK I made it to run, but I don't know how to put it in homebrew, I leave that to you
![image](https://user-images.githubusercontent.com/11816952/60963009-f8789600-a30f-11e9-98fb-73527eb4428b.png)

**Comment by BishopWolf** [comment]
@lpozo @codeshard  check this out
```bash
E15TY:videomorph alexvergaragil$ git push --set-upstream origin MacOS-Support
Username for 'https://github.com': BishopWolf
Password for 'https://BishopWolf@github.com': 
remote: Permission to videomorph-dev/videomorph.git denied to BishopWolf.
fatal: impossible d'accéder à 'https://github.com/videomorph-dev/videomorph/' : The requested URL returned error: 403
```

**Comment by BishopWolf** [comment]
@codeshard thanks for the invitation
```bash
E15TY:videomorph alexvergaragil$ git push --set-upstream origin MacOS-Support
Username for 'https://github.com': BishopWolf
Password for 'https://BishopWolf@github.com': 
Total 0 (delta 0), réutilisés 0 (delta 0)
remote: 
remote: Create a pull request for 'MacOS-Support' on GitHub by visiting:
remote:      https://github.com/videomorph-dev/videomorph/pull/new/MacOS-Support
remote: 
To https://github.com/videomorph-dev/videomorph
 * [new branch]      MacOS-Support -> MacOS-Support
La branche 'MacOS-Support' est paramétrée pour suivre la branche distante 'MacOS-Support' depuis 'origin'.
```

**Comment by PhaserEditor2D** [comment]
Hi!

So, is there macOS support?

I don't have experience compiling Qt apps in macOS, but I can try.

**Comment by BishopWolf** [comment]
@PhaserEditor2D it is working on my Mac if that's what you mean

**Comment by PhaserEditor2D** [comment]
Hi @BishopWolf 

Good. But I don't see any distribution file. I mean, in the releases assets.

I guess I should execute it from source.

**Comment by leonel-lordford** [comment]
Hi there @PhaserEditor2D @BishopWolf !

Thanks for the messages and updates! We might be releasing macOS native packages soon, since some members of the team are now able to use a MacBook... So stay tuned!

**Comment by PhaserEditor2D** [comment]
Nice! Thanks!
