### ISSUE TITLE
Retrieving video properties crashes

### ISSUE THREAD

**Issue by Dapid** [videomorph-dev/videomorph#71]
After adding a video to the list of tasks I right-clicked on the menu, and when selecting "Properties", I got the following traceback

```Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/videomorph/forms/videomorph.py", line 679, in show_video_info
    info_dlg = InfoDialog(parent=self,
  File "/usr/lib/python3.9/site-packages/videomorph/forms/info.py", line 186, in __init__
    self._show_video_info(self.position)
  File "/usr/lib/python3.9/site-packages/videomorph/forms/info.py", line 214, in _show_video_info
    task.video.audio_info['codec_name'])
KeyError: 'codec_name'
```

Using Videomorph 1.4.1-5 from rpmfusion on Fedora.

**Comment by ferdnyc** [comment]
I don't think this is still a problem — at least, I can't reproduce with the current videomorph-1.4.1-17.fc43.noarch on Fedora 43.

(Hmm, I should point out to the maintainers that videomorph 1.5 is released. Although I see it's not tagged in GitHub Releases, which is probably why it escaped their notice.)
